### ISSUE TITLE
RxJava2: Create an examples handing backpressure

### ISSUE THREAD

**Issue by marcinkunert** [kaushikgopal/RxJava-Android-Samples#87]
Since we soon will have RxJava2 here (#83) it would be nice to have examples that handle backpressure. Do you have any ideas for good examples?

**Comment by kaushikgopal** [comment]
yeah i've been thinking about this. Couple of points:

* By default we should be using `Flowable`s everywhere as good Rx citizens. Using Flowables inherently add the notion of backpressure but we obv. don't call it out explicitly.
* That being said the pagination example, has a high likelihood of running into a BackPressure exception, which is why that's [been handled there](https://github.com/kaushikgopal/RxJava-Android-Samples/blob/master/app/src/main/java/com/morihacky/android/rxjava/pagination/PaginationAutoFragment.java#L69)
* the problem with having an example just demoing BackPressure is that it doesn't go in the spirit of actual "examples". it's more a demo of an implementation detail (which is fine and a great thing to know) but might have to stick to keeping this repo as a "learn Rx by example" vs just "learn Rx"

if that makes sense.

**Comment by kaushikgopal** [comment]
going to go ahead and close this. if you feel differently feel free to reopen again with your thoughts
